In [1]:
import geopandas as gpd
import pandas as pd

1. Load Hasil Task 6

In [ ]:
path_input = "../data/input/Analisis_Risiko_Banjir_Terhadap_Tutupan_Lahan_Jaksel.geojson"

gdf = gpd.read_file(path_input)

print("Data berhasil dimuat")
gdf.head()

Data berhasil dimuat

,ID_PROV_1,PROVINSI_1,ID_KABKOT_1,KABKOT_1,ID_KEC_1,KECAMATAN_1,ID_DESA_1,DESA_1,KELAS_RISIKO,fid,...,DESA_2,TUTUPAN_LAHAN,longitude,latitude,q,r,Luas_m2,SKOR_TOTAL,KETERANGAN_RISIKO,geometry
0,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,123,...,GROGOL UTARA,LAHAN TERBANGUN,106.786794,-6.216845,27422,-15096,34331.849468,5,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((106.78463 -6.20674 0, 106.78477 -6..."
1,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,124,...,GROGOL UTARA,LAHAN TERBUKA,106.787834,-6.216594,27422,-15096,4355.941075,4,Risiko Tinggi,"POLYGON Z ((106.78315 -6.20696 0, 106.78316 -6..."
2,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,124,...,GROGOL UTARA,LAHAN TERBUKA,106.787834,-6.216594,27422,-15096,614.056619,4,Risiko Tinggi,"POLYGON Z ((106.78521 -6.20679 0, 106.78528 -6..."
3,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,123,...,GROGOL UTARA,LAHAN TERBANGUN,106.786794,-6.216845,27422,-15096,4826.994023,5,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((106.78765 -6.20732 0, 106.78772 -6..."
4,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,123,...,GROGOL UTARA,LAHAN TERBANGUN,106.786794,-6.216845,27422,-15096,3229.648951,5,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((106.78959 -6.20821 0, 106.78963 -6..."

2. Filter Zona Prioritas dengan Skor Tinggi (>= 4)

In [5]:
gdf_prioritas = gdf[gdf['SKOR_TOTAL'] >= 4].copy()

print("Jumlah zona prioritas:", len(gdf_prioritas))
gdf_prioritas.head()

Jumlah zona prioritas: 3366

,ID_PROV_1,PROVINSI_1,ID_KABKOT_1,KABKOT_1,ID_KEC_1,KECAMATAN_1,ID_DESA_1,DESA_1,KELAS_RISIKO,fid,...,DESA_2,TUTUPAN_LAHAN,longitude,latitude,q,r,Luas_m2,SKOR_TOTAL,KETERANGAN_RISIKO,geometry
0,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,123,...,GROGOL UTARA,LAHAN TERBANGUN,106.786794,-6.216845,27422,-15096,34331.849468,5,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((106.78463 -6.20674 0, 106.78477 -6..."
1,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,124,...,GROGOL UTARA,LAHAN TERBUKA,106.787834,-6.216594,27422,-15096,4355.941075,4,Risiko Tinggi,"POLYGON Z ((106.78315 -6.20696 0, 106.78316 -6..."
2,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,124,...,GROGOL UTARA,LAHAN TERBUKA,106.787834,-6.216594,27422,-15096,614.056619,4,Risiko Tinggi,"POLYGON Z ((106.78521 -6.20679 0, 106.78528 -6..."
3,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,123,...,GROGOL UTARA,LAHAN TERBANGUN,106.786794,-6.216845,27422,-15096,4826.994023,5,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((106.78765 -6.20732 0, 106.78772 -6..."
4,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,123,...,GROGOL UTARA,LAHAN TERBANGUN,106.786794,-6.216845,27422,-15096,3229.648951,5,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((106.78959 -6.20821 0, 106.78963 -6..."

3. Hitung Luas dan Ranking

In [4]:
# Ubah ke CRS meter untuk hitung luas
gdf_prioritas = gdf_prioritas.to_crs(epsg=3857)

# Hitung luas
gdf_prioritas['LUAS_M2'] = gdf_prioritas.geometry.area

# Ranking berdasarkan skor & luas
gdf_prioritas = gdf_prioritas.sort_values(
    ['SKOR_TOTAL', 'LUAS_M2'],
    ascending=[False, False]
)

gdf_prioritas.head()

,ID_PROV_1,PROVINSI_1,ID_KABKOT_1,KABKOT_1,ID_KEC_1,KECAMATAN_1,ID_DESA_1,DESA_1,KELAS_RISIKO,fid,...,TUTUPAN_LAHAN,longitude,latitude,q,r,Luas_m2,SKOR_TOTAL,KETERANGAN_RISIKO,geometry,LUAS_M2
2029,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.01,TEBET,31.74.01.1005,BUKIT DURI,TINGGI,17,...,LAHAN TERBANGUN,106.858740,-6.220756,27441,-15106,971688.026901,6,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((11895048.055 -694262.689 0, 118950...",971688.026901
3330,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.10,PESANGGRAHAN,31.74.10.1005,ULUJAMI,TINGGI,262,...,LAHAN TERBANGUN,106.763442,-6.236103,27416,-15098,969735.654960,6,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((11884524.684 -696535.103 0, 118845...",969735.654960
2656,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.01,TEBET,31.74.01.1007,MANGGARAI,TINGGI,22,...,LAHAN TERBANGUN,106.850985,-6.213541,27439,-15104,890017.225612,6,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((11894247.864 -693155.913 0, 118942...",890017.225612
2211,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,TINGGI,123,...,LAHAN TERBANGUN,106.786794,-6.216845,27422,-15096,725856.240900,6,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((11888260 -693311.337 0, 11888060 -...",725856.240901
2736,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.04,PASAR MINGGU,31.74.04.1005,PEJATEN TIMUR,TINGGI,98,...,LAHAN TERBANGUN,106.848664,-6.280093,27438,-15118,639045.789771,6,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((11894347.888 -702111.336 0, 118944...",639045.789771

4. Ambil Top 5 Zona Mitigasi

In [6]:
zona_top5 = gdf_prioritas.head(5)

zona_top5

,ID_PROV_1,PROVINSI_1,ID_KABKOT_1,KABKOT_1,ID_KEC_1,KECAMATAN_1,ID_DESA_1,DESA_1,KELAS_RISIKO,fid,...,DESA_2,TUTUPAN_LAHAN,longitude,latitude,q,r,Luas_m2,SKOR_TOTAL,KETERANGAN_RISIKO,geometry
0,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,123,...,GROGOL UTARA,LAHAN TERBANGUN,106.786794,-6.216845,27422,-15096,34331.849468,5,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((106.78463 -6.20674 0, 106.78477 -6..."
1,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,124,...,GROGOL UTARA,LAHAN TERBUKA,106.787834,-6.216594,27422,-15096,4355.941075,4,Risiko Tinggi,"POLYGON Z ((106.78315 -6.20696 0, 106.78316 -6..."
2,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,124,...,GROGOL UTARA,LAHAN TERBUKA,106.787834,-6.216594,27422,-15096,614.056619,4,Risiko Tinggi,"POLYGON Z ((106.78521 -6.20679 0, 106.78528 -6..."
3,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,123,...,GROGOL UTARA,LAHAN TERBANGUN,106.786794,-6.216845,27422,-15096,4826.994023,5,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((106.78765 -6.20732 0, 106.78772 -6..."
4,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,123,...,GROGOL UTARA,LAHAN TERBANGUN,106.786794,-6.216845,27422,-15096,3229.648951,5,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((106.78959 -6.20821 0, 106.78963 -6..."

In [7]:
# Kembalikan ke WGS84
zona_top5 = zona_top5.to_crs(epsg=4326)

zona_top5.head()

,ID_PROV_1,PROVINSI_1,ID_KABKOT_1,KABKOT_1,ID_KEC_1,KECAMATAN_1,ID_DESA_1,DESA_1,KELAS_RISIKO,fid,...,DESA_2,TUTUPAN_LAHAN,longitude,latitude,q,r,Luas_m2,SKOR_TOTAL,KETERANGAN_RISIKO,geometry
0,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,123,...,GROGOL UTARA,LAHAN TERBANGUN,106.786794,-6.216845,27422,-15096,34331.849468,5,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((106.78463 -6.20674 0, 106.78477 -6..."
1,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,124,...,GROGOL UTARA,LAHAN TERBUKA,106.787834,-6.216594,27422,-15096,4355.941075,4,Risiko Tinggi,"POLYGON Z ((106.78315 -6.20696 0, 106.78316 -6..."
2,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,124,...,GROGOL UTARA,LAHAN TERBUKA,106.787834,-6.216594,27422,-15096,614.056619,4,Risiko Tinggi,"POLYGON Z ((106.78521 -6.20679 0, 106.78528 -6..."
3,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,123,...,GROGOL UTARA,LAHAN TERBANGUN,106.786794,-6.216845,27422,-15096,4826.994023,5,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((106.78765 -6.20732 0, 106.78772 -6..."
4,31,DKI JAKARTA,31.74,KOTA ADM. JAKARTA SELATAN,31.74.05,KEBAYORAN LAMA,31.74.05.1004,GROGOL UTARA,SEDANG,123,...,GROGOL UTARA,LAHAN TERBANGUN,106.786794,-6.216845,27422,-15096,3229.648951,5,Risiko Sangat Tinggi (Prioritas Utama),"POLYGON Z ((106.78959 -6.20821 0, 106.78963 -6..."

5. Export ke folder Output

In [8]:
path_output = "../data/output/Zona_Top5_Prioritas.geojson"

zona_top5.to_file(path_output, driver="GeoJSON")

print("File berhasil disimpan di:", path_output)

File berhasil disimpan di: ../data/output/Zona_Top5_Prioritas.geojson